/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arcsoft_ais_arcvc_jni_P2PClient */

#ifndef _Included_com_arcsoft_ais_arcvc_jni_P2PClient
#define _Included_com_arcsoft_ais_arcvc_jni_P2PClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arcsoft_ais_arcvc_jni_P2PClient
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_arcsoft_ais_arcvc_jni_P2PClient_nativeInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_arcsoft_ais_arcvc_jni_P2PClient
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_arcsoft_ais_arcvc_jni_P2PClient_nativeUninit
  (JNIEnv *, jobject);

/*
 * Class:     com_arcsoft_ais_arcvc_jni_P2PClient
 * Method:    sendMsg
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_arcsoft_ais_arcvc_jni_P2PClient_sendMsg
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_arcsoft_ais_arcvc_jni_P2PClient
 * Method:    getLocalGpid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_arcsoft_ais_arcvc_jni_P2PClient_getLocalGpid
  (JNIEnv *, jobject);

/*
 * Class:     com_arcsoft_ais_arcvc_jni_P2PClient
 * Method:    startRTPSession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_arcsoft_ais_arcvc_jni_P2PClient_startRTPSession
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_arcsoft_ais_arcvc_jni_P2PClient
 * Method:    send264Packet
 * Signature: (Ljava/lang/String;Lcom/arcsoft/ais/arcvc/jni/H264Nal;)V
 */
JNIEXPORT void JNICALL Java_com_arcsoft_ais_arcvc_jni_P2PClient_send264Packet
  (JNIEnv *, jobject, jstring, jobject, jlong);

JNIEXPORT void JNICALL Java_com_arcsoft_ais_arcvc_jni_P2PClient_sendAACESData
  (JNIEnv *, jobject, jbyteArray, jint, jlong);
/*
 * Class:     com_arcsoft_ais_arcvc_jni_P2PClient
 * Method:    sendAACPacket
 * Signature: (Ljava/lang/String;Lcom/arcsoft/ais/arcvc/jni/AACNal;)V
 */
JNIEXPORT void JNICALL Java_com_arcsoft_ais_arcvc_jni_P2PClient_sendAACPacket
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
